### ISSUE TITLE
Code for summary generation from the given model is not provided

### ISSUE THREAD

**Issue by tarunyadav** [CannyLab/summary_loop#17]
You mentioned "Releasing the 11,490 summaries generated by the Summary Loop model (summary_loop_length46.bin) on the CNN/DM test set." and provided the json file "cnndm_test_summary_loop.json". Is there any code to get the json file(summaries) from the given model(.bin). If you have such code, then please share.

**Comment by tingofurro** [comment]
With the latest release of the Summary Loop model card ( https://huggingface.co/philippelaban/summary_loop46) , you should be able to produce summaries of similar quality.

It will be difficult to reproduce the exact same summaries, since the version change in HF has made very few variables change paths, which led to the model changing very slightly. You should however be getting summaries with similar quality (roughly measured in terms of ROUGE).

You can use HF's standard generation method with a beam-search (`num_beams`) argument. I believe we used beam-size 4, but it could also have been 6 or 8.

Good luck!
